# Generated by Django 2.2 on 2022-09-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_auto_20220907_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
