# Generated by Django 2.2 on 2022-09-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_auto_20220907_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='adhaar',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
