# Generated by Django 2.2 on 2022-09-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0004_auto_20220908_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
