# Generated by Django 2.2 on 2022-09-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0005_auto_20220908_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('stock', models.IntegerField()),
                ('vno', models.IntegerField()),
                ('stockid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('vtype', models.CharField(max_length=20)),
                ('tempno', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
