# Generated by Django 2.2 on 2022-09-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0006_auto_20220908_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock',
        ),
    ]
