# Generated by Django 2.2 on 2022-09-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0007_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('stock', models.IntegerField()),
                ('vno', models.IntegerField()),
                ('stockid', models.IntegerField(primary_key=True, serialize=False)),
                ('VehicleForeign', models.ForeignKey(on_delete=None, to='showroom.vehicle')),
            ],
        ),
    ]
