# Generated by Django 2.2 on 2022-09-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0008_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='VehicleForeign',
            new_name='VehicleNum',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='vno',
        ),
    ]
