# Generated by Django 2.2 on 2022-09-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0011_auto_20220910_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='VehicleNum',
            field=models.ForeignKey(null=True, on_delete=None, to='showroom.vehicle'),
        ),
    ]
