# Generated by Django 2.2 on 2022-09-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0012_auto_20220911_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_by_admin',
            fields=[
                ('bookingid', models.IntegerField(primary_key=True, serialize=False)),
                ('adminid', models.ForeignKey(on_delete=None, to='showroom.staff')),
                ('stockid', models.ForeignKey(on_delete=None, to='showroom.stock')),
            ],
        ),
    ]
